version: "3.8"

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbsparkles:/data/db
    environment:
      MONGO_INITDB_DATABASE: sparkles

volumes:
  dbsparkles: