name: Kotlin CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MICRONAUT_ENVIRONMENTS: local

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test jacocoTestReport

      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            **/build/reports/tests

      - name: Archive coverage results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results
          path: |
            **/build/reports/jacoco

      - name: Create coverage-data directory and copy contents
        run: |
          mkdir -p JVM/intellij-coverage-agent/gradle/.qodana/code-coverage
          cp -R JVM/intellij-coverage-agent/gradle/build/kover/bin-reports/* JVM/intellij-coverage-agent/gradle/.qodana/code-coverage/

      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: gradle-coverage-data.zip
          path: JVM/intellij-coverage-agent/gradle/.qodana/code-coverage

      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_GRADLE }}
        with:
          args: "-i,JVM/intellij-coverage-agent/gradle,--linter,jetbrains/qodana-jvm:2023.2-eap"
          pr-mode: false